### ISSUE TITLE
Undefined variable: langs

### ISSUE THREAD

**Issue by masadi** [coreui/coreui-free-laravel-admin-template#12]
Facade\Ignition\Exceptions\ViewException
Undefined variable: langs (View: ___\resources\views\dashboard\editmenu\show.blade.php) when accessing http://localhost:8000/menu/element/show?id=1

**Comment by rakieta2015** [comment]
It has just been fixed by this commit:[Fix: Remove langs from show menu element (show.blage.php) ](https://github.com/coreui/coreui-free-laravel-admin-template/commit/843f2633120e9124ddec165c05e8f076830f7a6c)
Thank you for your help in finding this problem.
