### ISSUE TITLE
Error running npm run dev

### ISSUE THREAD

**Issue by japc-74** [coreui/coreui-free-laravel-admin-template#13]
Hello guys. I got the next error trying to run npm run dev

`$ npm run dev

> @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2 dev /home/xxx/public_html/demo
> npm run development

> @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2 development /home/xxx/public_html/demo
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

node[31065]: pthread_create: Resource temporarily unavailable
10% building 1/1 modules 0 activenpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2 development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2020-03-05T07_32_12_246Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2 dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2020-03-05T07_32_12_260Z-debug.log`

And here is the content of log:

`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'development' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2~predevelopment: @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2
6 info lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2~development: @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2
7 verbose lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2~development: unsafe-perm in lifecycle true
8 verbose lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2~development: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/xxx/public_html/demo/node_modules/.bin:/usr/local/li$
9 verbose lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2~development: CWD: /home/xxx/public_html/demo
10 silly lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2~development: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
11 silly lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2~development: Returned: code: 1  signal: null
12 info lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2~development: Failed to exec development script
13 verbose stack Error: @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpac$
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2
15 verbose cwd /home/xxx/public_html/demo
16 verbose Linux 3.10.0-957.5.1.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "development"
18 verbose node v9.8.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 1
23 error Failed at the @coreui/coreui-free-laravel-admin-template@1.0.0-alpha.2 development script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

`

**Comment by rakieta2015** [comment]
This part of your output:
`node[31065]: pthread_create: Resource temporarily unavailable`
Means the problem is in your environment. 
For example this can be limits the number of processes and threads for user.
Or limit maximum number of threads per process. There is no single solution here, because the exact source of the problem is unknown, you have to discover the cause that lies in your operating system.

**Comment by japc-74** [comment]
Thanks for your reply, you were right, the problem was on my side
Unfortunately npm error messages really sucks! what I did was to login as root and run 
it works!
