### ISSUE TITLE
error ,  when  npm run dev 

### ISSUE THREAD

**Issue by marol1210** [coreui/coreui-free-laravel-admin-template#18]
the same code ,  migrate to aliycloud ,  then  setup  , npm run dev ,  go wrong

thanks help~

<img width="1500" alt="WX20200327-100518@2x" src="https://user-images.githubusercontent.com/7519301/77713882-8c130380-7012-11ea-9604-1a73559eea33.png">

**Comment by marol1210** [comment]
npm debug:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
> 2 info using npm@3.10.10
> 3 info using node@v6.17.1
> 4 verbose run-script [ 'predev', 'dev', 'postdev' ]
> 5 info lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1~predev: @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1
> 6 silly lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1~predev: no script for predev, continuing
> 7 info lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1~dev: @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1
> 8 verbose lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1~dev: unsafe-perm in lifecycle true
> 9 verbose lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/data/www/kerastase/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.7.0_80/bin:/usr/local/subversion/bin:/root/bin:/data/db/oracle/product/11gr2/bin:/root/bin
> 10 verbose lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1~dev: CWD: /data/www/kerastase
> 11 silly lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1~dev: Args: [ '-c', 'npm run development' ]
> 12 silly lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1~dev: Returned: code: 1  signal: null
> 13 info lifecycle @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1~dev: Failed to exec dev script
> 14 verbose stack Error: @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1 dev: `npm run development`
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at EventEmitter.emit (events.js:191:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 14 verbose stack     at emitTwo (events.js:106:13)
> 14 verbose stack     at ChildProcess.emit (events.js:191:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:920:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
> 15 verbose pkgid @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1
> 16 verbose cwd /data/www/kerastase
> 17 error Linux 3.10.0-957.1.3.el7.x86_64
> 18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
> 19 error node v6.17.1
> 20 error npm  v3.10.10
> 21 error code ELIFECYCLE
> 22 error @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1 dev: `npm run development`
> 22 error Exit status 1
> 23 error Failed at the @coreui/coreui-free-laravel-admin-template@1.0.0-beta.1 dev script 'npm run development'.
> 23 error Make sure you have the latest version of node.js and npm installed.
> 23 error If you do, this is most likely a problem with the @coreui/coreui-free-laravel-admin-template package,
> 23 error not with npm itself.
> 23 error Tell the author that this fails on your system:
> 23 error     npm run development
> 23 error You can get information on how to open an issue for this project with:
> 23 error     npm bugs @coreui/coreui-free-laravel-admin-template
> 23 error Or if that isn't available, you can get their info via:
> 23 error     npm owner ls @coreui/coreui-free-laravel-admin-template
> 23 error There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by marchershey** [comment]
Check your Node and NPM versions.

```
npm@3.10.10
node@v6.17.1
```

NPM's latest version is 6.14.4 and Node's latest version is 13.12... 

My first suggestion would be to update them to their latest versions and then try again.

**Comment by marol1210** [comment]
thanks a lot.   
I done  it.
@marchershey
