### ISSUE TITLE
Use of deprecated features

### ISSUE THREAD

**Issue by rabol** [coreui/coreui-free-laravel-admin-template#23]
Just tried a clean installation and get this:

Deprecation Notice: Class Tests\Unit\CoreUITest located in ./tests/Unit/@aCoreUITest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by rakieta2015** [comment]
Fixed in new release: [1.0.0-beta.2](https://github.com/coreui/coreui-free-laravel-admin-template/releases/tag/1.0.0-beta.2)
