### ISSUE TITLE
Overlayed top menu on smartphone device size preview

### ISSUE THREAD

**Issue by khazefa** [coreui/coreui-free-laravel-admin-template#4]
I have installed the fresh clone from this repo, but when i toggle screen to smartphone size, it come out like this, please tell me what i need to do?
![Screen Shot 2019-12-24 at 8 15 06 PM](https://user-images.githubusercontent.com/9564164/71414681-98da3100-268a-11ea-978b-bd4cc24d61ff.png)
![Screen Shot 2019-12-24 at 8 15 17 PM](https://user-images.githubusercontent.com/9564164/71414682-9972c780-268a-11ea-86cf-2cea3f202dcc.png)
![Screen Shot 2019-12-24 at 8 15 40 PM](https://user-images.githubusercontent.com/9564164/71414683-9a0b5e00-268a-11ea-8966-ca167b202b99.png)

**Comment by rakieta2015** [comment]
The problem has been fixed.
To fix it in an older version: 
-open resources/views/dashboard/shared/header.blade.php
-Change the line
FreelyPositionedMenus::render( $appMenus['top menu'] , 'c-header-');
to
FreelyPositionedMenus::render( $appMenus['top menu'] , 'c-header-', 'd-md-down-none');
