### ISSUE TITLE
Logout doesn't work.

### ISSUE THREAD

**Issue by airliajsmith** [coreui/coreui-free-laravel-admin-template#40]
I just cloned this project today. I haven't changed anything that would affect this. When I try to logout, it just refreshes the page.

**Comment by rakieta2015** [comment]
At the moment I don't see any malfunction in the logout. 
Are you sure you're really clicking on the logout?
Maybe you are clicking on the sidebar login link again?
![logout](https://user-images.githubusercontent.com/34374525/89514410-1b58d080-d7d6-11ea-8464-15bdddd3932e.jpg)

**Comment by airliajsmith** [comment]
When was it fixed? I just cloned it yesterday and it's not working.

**Comment by airliajsmith** [comment]
I think it was a php version issue. I was running 7.2.3. I started with a fresh install of Laravel, then began integrating the files.

**Comment by rakieta2015** [comment]
Was fixed after this issue was opened  [(in this release 1.0.4)](https://github.com/coreui/coreui-free-laravel-admin-template/releases/tag/1.0.4)
