### ISSUE TITLE
Menu links go to localhost, which doesn't work.

### ISSUE THREAD

**Issue by airliajsmith** [coreui/coreui-free-laravel-admin-template#41]
The links keep going to localhost, which doesn't work, but 127.0.0.1:8000 does. How do I make that change with your template?

Example: http://localhost/login is what I get when I click on the Login button on the left side.

**Comment by rakieta2015** [comment]
In the ".env" configuration file, there is a line: "APP_URL=". 
Just change its value to update the links in the sidebar. 
For example: APP_URL=http://127.0.0.1:8001

**Comment by airliajsmith** [comment]
I had to change settings in the hosts file to fix it. Thanks!
