### ISSUE TITLE
Tooltips in Card-Chart not show

### ISSUE THREAD

**Issue by vonsogt** [coreui/coreui-free-laravel-admin-template#6]
- after install and run the project, the default widgets card-chart not show any tooltips.
   got this warning too:
   `bar chart: "scales.[x/y]Axes.barPercentage" is deprecated. Please use "dataset.barPercentage" instead`
- and the route /widgets  as admin not found `js/coreui-chartjs.js`

**Comment by vonsogt** [comment]
the second problem, fixed by doing this PR:
#7

**Comment by vonsogt** [comment]
after I added this script in options:
```
tooltips: {
	enabled: true,
	callbacks: {
		label: function (tooltipItem, data) {
			return data.datasets[tooltipItem.datasetIndex].label + ' : ' + data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];
		}
	}
},
```
The tooltips become like this:

Pict1 - (added that options):
![image](https://user-images.githubusercontent.com/35516476/72510678-7350d980-387c-11ea-8629-18c8ba2f2f2f.png)

Pict2 (from https://coreui.io/react/demo/#/dashboard) :
![image](https://user-images.githubusercontent.com/35516476/72510763-92e80200-387c-11ea-80c9-d989236604a1.png)
Pict2a (from https://coreui.io/demo/3.0-beta.0/#main.html):
![image](https://user-images.githubusercontent.com/35516476/72511022-04c04b80-387d-11ea-82e4-013fd025e908.png)


It is different from picture number 1 and [2, 2a], @rakieta2015 did your tooltips show in this project?
or should we change or add the *.js file using this code?

**Comment by xidedix** [comment]
We use custom tooltips for those charts. If they are not showing, then we have to find out why.

**Comment by xidedix** [comment]
fixed - thanks @vonsogt
