### ISSUE TITLE
Sidebar broken.

### ISSUE THREAD

**Issue by airliajsmith** [coreui/coreui-free-laravel-admin-template#68]
When I came in to work on Tuesday, July 6th I noticed a new error: 

Uncaught TypeError: Cannot set property 'Constructor' of undefined. 

It appears to be linked to this CDN:

https://unpkg.com/@coreui/coreui/dist/js/coreui.bundle.min.js

When I comment it out, the error goes away, but the sidebar has issues either way:

- dropdown doesn't work
- collapse doesn't work

**Comment by ctyler69** [comment]
> When I came in to work on Tuesday, July 6th I noticed a new error:
> 
> Uncaught TypeError: Cannot set property 'Constructor' of undefined.
> 
> It appears to be linked to this CDN:
> 
> https://unpkg.com/@coreui/coreui/dist/js/coreui.bundle.min.js
> 
> When I comment it out, the error goes away, but the sidebar has issues either way:
> 
> * dropdown doesn't work
> * collapse doesn't work

Hello,
I am having the same issue but in my case, I do not have any styling at all. Commenting out does not resolve the issue.

**Comment by mrholek** [comment]
Check this https://github.com/coreui/coreui/issues/235

**Comment by airliajsmith** [comment]
Not sure how I missed that post. I searched for so long. 

I'll give it a try. Thanks!

**Comment by airliajsmith** [comment]
Now I have a new issue when linking to the new file:

CoreUI's sidebar require Perfect Scrollbar

**Comment by mrholek** [comment]
Try this `<script src="https://unpkg.com/@coreui/coreui@3.4.0/dist/js/coreui.bundle.min.js"></script>`

**Comment by airliajsmith** [comment]
That fixed it. Thanks!!
